"""Constants for the Beoremote Halo client."""

from typing import Final

VERSION: Final = "1.0.1"

WEBSOCKET_TIMEOUT: Final = 5.0

MIN_VALUE: Final = 0
MAX_VALUE: Final = 100

WHEEL_COUNTS_MIN: Final = -5
WHEEL_COUNTS_MAX: Final = 5

# MIN_PAGES and MIN_BUTTONS are supposed to be 1 according to the AsyncAPI spec
# That makes setting up a configuration more cumbersome than necessary, so it is ignored here
MIN_PAGES: Final = 0
MIN_PAGES_VALIDATION: Final = 1
MAX_PAGES: Final = 3

MIN_BUTTONS: Final = 0
MIN_BUTTONS_VALIDATION: Final = 1
MAX_BUTTONS: Final = 8

BUTTON_CONTENT_TEXT_MIN_LENGTH: Final = 0
BUTTON_CONTENT_TEXT_MAX_LENGTH: Final = 6
BUTTON_TITLE_MIN_LENGTH: Final = 0
BUTTON_TITLE_MAX_LENGTH: Final = 15
BUTTON_SUBTITLE_MIN_LENGTH: Final = 0
BUTTON_SUBTITLE_MAX_LENGTH: Final = 15

# These are approximate numbers
PAGE_TITLE_MIN_LENGTH: Final = 0
PAGE_TITLE_MAX_LENGTH: Final = 40
NOTIFICATION_TITLE_MIN_LENGTH: Final = 0
NOTIFICATION_TITLE_MAX_LENGTH: Final = 40
NOTIFICATION_SUBTITLE_MIN_LENGTH: Final = 0
NOTIFICATION_SUBTITLE_MAX_LENGTH: Final = 350
NOTIFICATION_SUBTITLE_MIN_LINE_LENGTH: Final = 0
NOTIFICATION_SUBTITLE_MAX_LINE_LENGTH: Final = 60
NOTIFICATION_SUBTITLE_MIN_LINES: Final = 0
NOTIFICATION_SUBTITLE_MAX_LINES: Final = 5
